package com.salaboy.lego.wedo;

import com.salaboy.rolo.model.*;

import com.salaboy.rolo.api.*;
import com.salaboy.rolo.api.Motor.*;

import org.drools.common.*;
import org.kie.event.rule.*;
import org.kie.runtime.rule.*;
import org.kie.runtime.*;
import org.kie.runtime.KnowledgeRuntime;

declare DistanceReport
    @role(event)
    @expires(1s)
end


rule "test sensor"
    when
        DistanceReport( $d: distance ) over window:time( 300ms ) from entry-point "distance-sensor"
    then
        System.out.println(" - Distance: "+$d);
end











