/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.salaboy.rolo.hardware.test.ui;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author salaboy
 */
public class HardwareTestUIJFrame extends javax.swing.JFrame {

    private RoloClientConnector roloClientConnector;
    private boolean connected = false;
    /**
     * Creates new form RoloUIJFrame
     */
    public HardwareTestUIJFrame() {
        initComponents();
        roloClientConnector = new RoloClientConnector("rolo-ui", new CommandClientHandler(this));
        
        
    }

    public JTextArea getNotificationjTextArea() {
        return notificationjTextArea;
    }

    public JTextField getDistancejTextField() {
        return distancejTextField;
    }

    public JTextField getLightjTextField() {
        return lightjTextField;
    }

    public JTextField getTouchjTextField() {
        return touchjTextField;
    }

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * 
     * 
     */
    
    
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    backwardAjButton = new javax.swing.JButton();
    forwardAjButton = new javax.swing.JButton();
    stopAjButton = new javax.swing.JButton();
    motorAjSlider = new javax.swing.JSlider();
    monitorMotorAjCheckBox = new javax.swing.JCheckBox();
    jPanel2 = new javax.swing.JPanel();
    jScrollPane1 = new javax.swing.JScrollPane();
    notificationjTextArea = new javax.swing.JTextArea();
    jButton1 = new javax.swing.JButton();
    jPanel3 = new javax.swing.JPanel();
    serverAddressjTextField = new javax.swing.JTextField();
    connectjButton = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();
    statusjLabel = new javax.swing.JLabel();
    localjCheckBox = new javax.swing.JCheckBox();
    jPanel4 = new javax.swing.JPanel();
    jLabel2 = new javax.swing.JLabel();
    distancejTextField = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    lightjTextField = new javax.swing.JTextField();
    touchjTextField = new javax.swing.JTextField();
    jLabel4 = new javax.swing.JLabel();
    distanceEnabledjCheckBox = new javax.swing.JCheckBox();
    lightEnabledjCheckBox = new javax.swing.JCheckBox();
    touchEnabledjCheckBox = new javax.swing.JCheckBox();
    globalEnabledjCheckBox = new javax.swing.JCheckBox();
    jPanel5 = new javax.swing.JPanel();
    backwardCjButton1 = new javax.swing.JButton();
    forwardCjButton1 = new javax.swing.JButton();
    stopCjButton1 = new javax.swing.JButton();
    motorCjSlider = new javax.swing.JSlider();
    jPanel6 = new javax.swing.JPanel();
    backwardBjButton2 = new javax.swing.JButton();
    forwardBjButton2 = new javax.swing.JButton();
    stopBjButton2 = new javax.swing.JButton();
    motorBjSlider = new javax.swing.JSlider();
    jPanel7 = new javax.swing.JPanel();
    backwardGlobaljButton = new javax.swing.JButton();
    forwardGlobaljButton = new javax.swing.JButton();
    stopGlobaljButton = new javax.swing.JButton();
    motorGlobaljSlider = new javax.swing.JSlider();
    jPanel8 = new javax.swing.JPanel();
    multiRotateLjButton = new javax.swing.JButton();
    multiRotateRjButton = new javax.swing.JButton();
    multiLookupjButton = new javax.swing.JButton();
    multiScanResultsjButton1 = new javax.swing.JButton();
    multiScanStopjButton = new javax.swing.JButton();
    multiScanCleanjButton = new javax.swing.JButton();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    multiRotateLjButton1 = new javax.swing.JButton();
    multiRotateLjButton2 = new javax.swing.JButton();
    multiRotateLjButton3 = new javax.swing.JButton();
    jPanel9 = new javax.swing.JPanel();
    backwardGlobaljButton2 = new javax.swing.JButton();
    servo180rightjButton1 = new javax.swing.JButton();
    servo180CenterjButton1 = new javax.swing.JButton();
    servo180jSlider1 = new javax.swing.JSlider();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Motor A"));

    backwardAjButton.setText("Backward");
    backwardAjButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        backwardAjButtonActionPerformed(evt);
      }
    });

    forwardAjButton.setText("Forward");
    forwardAjButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        forwardAjButtonActionPerformed(evt);
      }
    });

    stopAjButton.setText("Stop");
    stopAjButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        stopAjButtonActionPerformed(evt);
      }
    });

    motorAjSlider.setMaximum(255);

    monitorMotorAjCheckBox.setText("Monitor");
    monitorMotorAjCheckBox.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        monitorMotorAjCheckBoxActionPerformed(evt);
      }
    });

    org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(jPanel1Layout.createSequentialGroup()
        .add(forwardAjButton)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(backwardAjButton)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(stopAjButton)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(motorAjSlider, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(monitorMotorAjCheckBox)
        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(forwardAjButton)
          .add(stopAjButton)
          .add(backwardAjButton))
        .add(214, 214, 214))
      .add(jPanel1Layout.createSequentialGroup()
        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
          .add(monitorMotorAjCheckBox)
          .add(motorAjSlider, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        .add(0, 0, Short.MAX_VALUE))
    );

    jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Notifications"));

    notificationjTextArea.setColumns(20);
    notificationjTextArea.setRows(5);
    jScrollPane1.setViewportView(notificationjTextArea);

    jButton1.setText("Clear");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(jScrollPane1)
          .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
            .add(0, 0, Short.MAX_VALUE)
            .add(jButton1)))
        .addContainerGap())
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(jPanel2Layout.createSequentialGroup()
        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 361, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .add(jButton1))
    );

    jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Settings"));

    serverAddressjTextField.setText("192.168.0.x");

    connectjButton.setText("Connect");
    connectjButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        connectjButtonActionPerformed(evt);
      }
    });

    jLabel1.setText("Status:");

    statusjLabel.setBackground(new java.awt.Color(153, 0, 0));
    statusjLabel.setForeground(new java.awt.Color(153, 0, 0));
    statusjLabel.setText("Disconnected");

    localjCheckBox.setText("Local?");
    localjCheckBox.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        localjCheckBoxActionPerformed(evt);
      }
    });

    org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
      jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(jPanel3Layout.createSequentialGroup()
        .addContainerGap()
        .add(serverAddressjTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 163, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(connectjButton)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(localjCheckBox)
        .add(18, 18, 18)
        .add(jLabel1)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
        .add(statusjLabel)
        .addContainerGap(64, Short.MAX_VALUE))
    );
    jPanel3Layout.setVerticalGroup(
      jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
        .add(localjCheckBox)
        .add(jLabel1)
        .add(statusjLabel)
        .add(serverAddressjTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .add(connectjButton))
    );

    jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Sensors"));

    jLabel2.setText("Distance:");

    jLabel3.setText("Light:");

    jLabel4.setText("Touch:");

    distanceEnabledjCheckBox.setText("Enabled?");
    distanceEnabledjCheckBox.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        distanceEnabledjCheckBoxActionPerformed(evt);
      }
    });

    lightEnabledjCheckBox.setText("Enabled?");
    lightEnabledjCheckBox.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        lightEnabledjCheckBoxActionPerformed(evt);
      }
    });

    touchEnabledjCheckBox.setText("Enabled?");
    touchEnabledjCheckBox.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        touchEnabledjCheckBoxActionPerformed(evt);
      }
    });

    globalEnabledjCheckBox.setText("Global Enabled?");
    globalEnabledjCheckBox.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        globalEnabledjCheckBoxActionPerformed(evt);
      }
    });

    org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
      jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(jPanel4Layout.createSequentialGroup()
        .addContainerGap()
        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
            .add(jPanel4Layout.createSequentialGroup()
              .add(jLabel2)
              .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
              .add(distancejTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 85, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
              .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
              .add(distanceEnabledjCheckBox))
            .add(jPanel4Layout.createSequentialGroup()
              .add(jLabel3)
              .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
              .add(lightjTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 87, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
              .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
              .add(lightEnabledjCheckBox))
            .add(jPanel4Layout.createSequentialGroup()
              .add(jLabel4)
              .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
              .add(touchjTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 86, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
              .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
              .add(touchEnabledjCheckBox)))
          .add(jPanel4Layout.createSequentialGroup()
            .add(162, 162, 162)
            .add(globalEnabledjCheckBox)))
        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel4Layout.setVerticalGroup(
      jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(jPanel4Layout.createSequentialGroup()
        .addContainerGap()
        .add(globalEnabledjCheckBox)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(distanceEnabledjCheckBox)
          .add(jLabel2)
          .add(distancejTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(lightjTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
          .add(jLabel3)
          .add(lightEnabledjCheckBox))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(touchjTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
          .add(jLabel4)
          .add(touchEnabledjCheckBox))
        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Motor C"));

    backwardCjButton1.setText("Backward");
    backwardCjButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        backwardCjButton1ActionPerformed(evt);
      }
    });

    forwardCjButton1.setText("Forward");
    forwardCjButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        forwardCjButton1ActionPerformed(evt);
      }
    });

    stopCjButton1.setText("Stop");
    stopCjButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        stopCjButton1ActionPerformed(evt);
      }
    });

    motorCjSlider.setMaximum(255);

    org.jdesktop.layout.GroupLayout jPanel5Layout = new org.jdesktop.layout.GroupLayout(jPanel5);
    jPanel5.setLayout(jPanel5Layout);
    jPanel5Layout.setHorizontalGroup(
      jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(jPanel5Layout.createSequentialGroup()
        .add(forwardCjButton1)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(backwardCjButton1)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(stopCjButton1)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(motorCjSlider, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel5Layout.setVerticalGroup(
      jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel5Layout.createSequentialGroup()
        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(forwardCjButton1)
          .add(stopCjButton1)
          .add(backwardCjButton1))
        .add(214, 214, 214))
      .add(jPanel5Layout.createSequentialGroup()
        .add(motorCjSlider, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .add(0, 0, Short.MAX_VALUE))
    );

    jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Motor B"));

    backwardBjButton2.setText("Backward");
    backwardBjButton2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        backwardBjButton2ActionPerformed(evt);
      }
    });

    forwardBjButton2.setText("Forward");
    forwardBjButton2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        forwardBjButton2ActionPerformed(evt);
      }
    });

    stopBjButton2.setText("Stop");
    stopBjButton2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        stopBjButton2ActionPerformed(evt);
      }
    });

    motorBjSlider.setMaximum(255);

    org.jdesktop.layout.GroupLayout jPanel6Layout = new org.jdesktop.layout.GroupLayout(jPanel6);
    jPanel6.setLayout(jPanel6Layout);
    jPanel6Layout.setHorizontalGroup(
      jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(jPanel6Layout.createSequentialGroup()
        .add(forwardBjButton2)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(backwardBjButton2)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(stopBjButton2)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(motorBjSlider, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel6Layout.setVerticalGroup(
      jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel6Layout.createSequentialGroup()
        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(forwardBjButton2)
          .add(stopBjButton2)
          .add(backwardBjButton2))
        .add(214, 214, 214))
      .add(jPanel6Layout.createSequentialGroup()
        .add(motorBjSlider, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .add(0, 0, Short.MAX_VALUE))
    );

    jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Global"));

    backwardGlobaljButton.setText("Backward");
    backwardGlobaljButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        backwardGlobaljButtonActionPerformed(evt);
      }
    });

    forwardGlobaljButton.setText("Forward");
    forwardGlobaljButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        forwardGlobaljButtonActionPerformed(evt);
      }
    });

    stopGlobaljButton.setText("Stop");
    stopGlobaljButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        stopGlobaljButtonActionPerformed(evt);
      }
    });

    motorGlobaljSlider.setMaximum(255);

    org.jdesktop.layout.GroupLayout jPanel7Layout = new org.jdesktop.layout.GroupLayout(jPanel7);
    jPanel7.setLayout(jPanel7Layout);
    jPanel7Layout.setHorizontalGroup(
      jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(jPanel7Layout.createSequentialGroup()
        .add(forwardGlobaljButton)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(backwardGlobaljButton)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(stopGlobaljButton)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(motorGlobaljSlider, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel7Layout.setVerticalGroup(
      jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel7Layout.createSequentialGroup()
        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .add(jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(forwardGlobaljButton)
          .add(stopGlobaljButton)
          .add(backwardGlobaljButton))
        .add(214, 214, 214))
      .add(jPanel7Layout.createSequentialGroup()
        .add(motorGlobaljSlider, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .add(0, 0, Short.MAX_VALUE))
    );

    jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Multi Actions"));

    multiRotateLjButton.setText("Rotate L");
    multiRotateLjButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        multiRotateLjButtonActionPerformed(evt);
      }
    });

    multiRotateRjButton.setText("Rotate R");
    multiRotateRjButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        multiRotateRjButtonActionPerformed(evt);
      }
    });

    multiLookupjButton.setText("Scan");
    multiLookupjButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        multiLookupjButtonActionPerformed(evt);
      }
    });

    multiScanResultsjButton1.setText("Scan Results");
    multiScanResultsjButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        multiScanResultsjButton1ActionPerformed(evt);
      }
    });

    multiScanStopjButton.setText("Scan Stop");
    multiScanStopjButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        multiScanStopjButtonActionPerformed(evt);
      }
    });

    multiScanCleanjButton.setText("Scan Clean");
    multiScanCleanjButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        multiScanCleanjButtonActionPerformed(evt);
      }
    });

    jLabel5.setText("Traction:");

    jLabel6.setText("Head:");

    multiRotateLjButton1.setText("B");
    multiRotateLjButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        multiRotateLjButton1ActionPerformed(evt);
      }
    });

    multiRotateLjButton2.setText("F");
    multiRotateLjButton2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        multiRotateLjButton2ActionPerformed(evt);
      }
    });

    multiRotateLjButton3.setText("180");
    multiRotateLjButton3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        multiRotateLjButton3ActionPerformed(evt);
      }
    });

    org.jdesktop.layout.GroupLayout jPanel8Layout = new org.jdesktop.layout.GroupLayout(jPanel8);
    jPanel8.setLayout(jPanel8Layout);
    jPanel8Layout.setHorizontalGroup(
      jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(jPanel8Layout.createSequentialGroup()
        .add(15, 15, 15)
        .add(jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
          .add(jLabel5)
          .add(jLabel6))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(jPanel8Layout.createSequentialGroup()
            .add(multiLookupjButton)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(multiScanResultsjButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 114, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(multiScanStopjButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 114, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(multiScanCleanjButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 114, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(0, 0, Short.MAX_VALUE))
          .add(jPanel8Layout.createSequentialGroup()
            .add(multiRotateRjButton)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(multiRotateLjButton)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(multiRotateLjButton2)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
            .add(multiRotateLjButton1)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(multiRotateLjButton3)))
        .addContainerGap())
    );
    jPanel8Layout.setVerticalGroup(
      jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel8Layout.createSequentialGroup()
        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .add(jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(multiRotateRjButton)
          .add(multiRotateLjButton)
          .add(jLabel5)
          .add(multiRotateLjButton1)
          .add(multiRotateLjButton2)
          .add(multiRotateLjButton3))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(multiLookupjButton)
          .add(multiScanResultsjButton1)
          .add(multiScanStopjButton)
          .add(multiScanCleanjButton)
          .add(jLabel6))
        .add(179, 179, 179))
    );

    jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Servo180"));

    backwardGlobaljButton2.setText("Left");
    backwardGlobaljButton2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        backwardGlobaljButton2ActionPerformed(evt);
      }
    });

    servo180rightjButton1.setText("Right");
    servo180rightjButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        servo180rightjButton1ActionPerformed(evt);
      }
    });

    servo180CenterjButton1.setText("Center");
    servo180CenterjButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        servo180CenterjButton1ActionPerformed(evt);
      }
    });

    servo180jSlider1.setMaximum(180);
    servo180jSlider1.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseReleased(java.awt.event.MouseEvent evt) {
        servo180jSlider1MouseReleased(evt);
      }
    });
    servo180jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
      public void stateChanged(javax.swing.event.ChangeEvent evt) {
        servo180jSlider1StateChanged(evt);
      }
    });
    servo180jSlider1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
      public void propertyChange(java.beans.PropertyChangeEvent evt) {
        servo180jSlider1PropertyChange(evt);
      }
    });

    org.jdesktop.layout.GroupLayout jPanel9Layout = new org.jdesktop.layout.GroupLayout(jPanel9);
    jPanel9.setLayout(jPanel9Layout);
    jPanel9Layout.setHorizontalGroup(
      jPanel9Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(jPanel9Layout.createSequentialGroup()
        .add(servo180rightjButton1)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(backwardGlobaljButton2)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(servo180CenterjButton1)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
        .add(servo180jSlider1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel9Layout.setVerticalGroup(
      jPanel9Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel9Layout.createSequentialGroup()
        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .add(jPanel9Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(servo180rightjButton1)
          .add(servo180CenterjButton1)
          .add(backwardGlobaljButton2))
        .add(214, 214, 214))
      .add(jPanel9Layout.createSequentialGroup()
        .add(servo180jSlider1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .add(0, 0, Short.MAX_VALUE))
    );

    org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .addContainerGap()
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(layout.createSequentialGroup()
            .add(jPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jPanel8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(0, 233, Short.MAX_VALUE))
          .add(layout.createSequentialGroup()
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
              .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .add(jPanel7, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .add(jPanel9, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
              .add(jPanel6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        .add(0, 0, 0))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .add(22, 22, 22)
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
          .add(layout.createSequentialGroup()
            .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(16, 16, 16)
            .add(jPanel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
            .add(jPanel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 62, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jPanel7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 62, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(16, 16, 16)
            .add(jPanel9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 62, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
          .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(jPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
          .add(jPanel8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 105, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(17, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void forwardAjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forwardAjButtonActionPerformed
        roloClientConnector.write("FORWARD-A:"+motorAjSlider.getValue());
        
    }//GEN-LAST:event_forwardAjButtonActionPerformed

    private void backwardAjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backwardAjButtonActionPerformed
        roloClientConnector.write("BACKWARD-A:"+motorAjSlider.getValue());
    }//GEN-LAST:event_backwardAjButtonActionPerformed

    private void connectjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectjButtonActionPerformed
        
        if(!connected){
            connected = roloClientConnector.connect(serverAddressjTextField.getText(), 5445);
            if(connected){
                statusjLabel.setText("Connected");
                statusjLabel.setForeground(Color.green);
                connectjButton.setText("Disconnect");
            }
        }else{
            try {
                roloClientConnector.disconnect();
            } catch (Exception ex) {
                Logger.getLogger(HardwareTestUIJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            connectjButton.setText("Connect");
            statusjLabel.setText("Disconnected");
            statusjLabel.setForeground(Color.red);
        }
        
    }//GEN-LAST:event_connectjButtonActionPerformed

    private void stopAjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopAjButtonActionPerformed
        // TODO add your handling code here:
        roloClientConnector.write("STOP-A:");
    }//GEN-LAST:event_stopAjButtonActionPerformed

  private void localjCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localjCheckBoxActionPerformed
    // TODO add your handling code here:
    if(localjCheckBox.isSelected()){
      serverAddressjTextField.setText("127.0.0.1");
    }else{
      serverAddressjTextField.setText("192.168.0.x");
    }
  }//GEN-LAST:event_localjCheckBoxActionPerformed

  private void backwardCjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backwardCjButton1ActionPerformed
    // TODO add your handling code here:
    roloClientConnector.write("BACKWARD-C:"+motorCjSlider.getValue());
    
  }//GEN-LAST:event_backwardCjButton1ActionPerformed

  private void forwardCjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forwardCjButton1ActionPerformed
    // TODO add your handling code here:
    roloClientConnector.write("FORWARD-C:"+motorCjSlider.getValue());
  }//GEN-LAST:event_forwardCjButton1ActionPerformed

  private void stopCjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopCjButton1ActionPerformed
    // TODO add your handling code here:
    roloClientConnector.write("STOP-C:");
  }//GEN-LAST:event_stopCjButton1ActionPerformed

  private void backwardBjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backwardBjButton2ActionPerformed
    // TODO add your handling code here:
    roloClientConnector.write("BACKWARD-B:"+motorBjSlider.getValue());
  }//GEN-LAST:event_backwardBjButton2ActionPerformed

  private void forwardBjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forwardBjButton2ActionPerformed
    // TODO add your handling code here:
    roloClientConnector.write("FORWARD-B:"+motorBjSlider.getValue());
  }//GEN-LAST:event_forwardBjButton2ActionPerformed

  private void stopBjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopBjButton2ActionPerformed
    // TODO add your handling code here:
    roloClientConnector.write("STOP-B:");
  }//GEN-LAST:event_stopBjButton2ActionPerformed

  private void backwardGlobaljButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backwardGlobaljButtonActionPerformed
    // TODO add your handling code here:
    roloClientConnector.write("BACKWARD-GLOBAL:"+motorGlobaljSlider.getValue());
  }//GEN-LAST:event_backwardGlobaljButtonActionPerformed

  private void forwardGlobaljButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forwardGlobaljButtonActionPerformed
    // TODO add your handling code here:
    roloClientConnector.write("FORWARD-GLOBAL:"+motorGlobaljSlider.getValue());
  }//GEN-LAST:event_forwardGlobaljButtonActionPerformed

  private void stopGlobaljButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopGlobaljButtonActionPerformed
    // TODO add your handling code here:
    roloClientConnector.write("STOP-GLOBAL:");
  }//GEN-LAST:event_stopGlobaljButtonActionPerformed

  private void distanceEnabledjCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_distanceEnabledjCheckBoxActionPerformed
    // TODO add your handling code here:
    if(distanceEnabledjCheckBox.isSelected()){
      roloClientConnector.write("SENSOR-ON:DISTANCE");
    }else{
      roloClientConnector.write("SENSOR-OFF:DISTANCE");
    }
  }//GEN-LAST:event_distanceEnabledjCheckBoxActionPerformed

  private void lightEnabledjCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lightEnabledjCheckBoxActionPerformed
    // TODO add your handling code here:
    if(lightEnabledjCheckBox.isSelected()){
      roloClientConnector.write("SENSOR-ON:LIGHT");
    }else{
      roloClientConnector.write("SENSOR-OFF:LIGHT");
    }
  }//GEN-LAST:event_lightEnabledjCheckBoxActionPerformed

  private void touchEnabledjCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_touchEnabledjCheckBoxActionPerformed
    // TODO add your handling code here:
    if(lightEnabledjCheckBox.isSelected()){
      roloClientConnector.write("SENSOR-ON:TOUCH");
    }else{
      roloClientConnector.write("SENSOR-OFF:TOUCH");
    }
  }//GEN-LAST:event_touchEnabledjCheckBoxActionPerformed

  private void globalEnabledjCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_globalEnabledjCheckBoxActionPerformed
    // TODO add your handling code here:
    if(lightEnabledjCheckBox.isSelected()){
      roloClientConnector.write("SENSOR-ON:ALL");
      lightEnabledjCheckBox.setSelected(true);
      touchEnabledjCheckBox.setSelected(true);
      distanceEnabledjCheckBox.setSelected(true);
    }else{
      roloClientConnector.write("SENSOR-OFF:ALL");
      lightEnabledjCheckBox.setSelected(false);
      touchEnabledjCheckBox.setSelected(false);
      distanceEnabledjCheckBox.setSelected(false);
    }
  }//GEN-LAST:event_globalEnabledjCheckBoxActionPerformed

  private void multiRotateLjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiRotateLjButtonActionPerformed
    // TODO add your handling code here:
    roloClientConnector.write("MULTI:ROTATE-LEFT");
  }//GEN-LAST:event_multiRotateLjButtonActionPerformed

  private void multiRotateRjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiRotateRjButtonActionPerformed
    // TODO add your handling code here:
    roloClientConnector.write("MULTI:ROTATE-RIGHT");
  }//GEN-LAST:event_multiRotateRjButtonActionPerformed

  private void backwardGlobaljButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backwardGlobaljButton2ActionPerformed
      // TODO add your handling code here:
    roloClientConnector.write("SERVO180:LEFT");
  }//GEN-LAST:event_backwardGlobaljButton2ActionPerformed

  private void servo180rightjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_servo180rightjButton1ActionPerformed
    // TODO add your handling code here:
    roloClientConnector.write("SERVO180:RIGHT");
  }//GEN-LAST:event_servo180rightjButton1ActionPerformed

  private void servo180CenterjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_servo180CenterjButton1ActionPerformed
    // TODO add your handling code here:
    roloClientConnector.write("SERVO180:CENTER");
  }//GEN-LAST:event_servo180CenterjButton1ActionPerformed

  private void servo180jSlider1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_servo180jSlider1MouseReleased
    // TODO add your handling code here:
    int angle = evt.getX();
    if(angle < 0){
      angle = 1;
    }if(angle > 180){
      angle = 179;
    }
    
    roloClientConnector.write("SERVO180:"+angle);
  }//GEN-LAST:event_servo180jSlider1MouseReleased

  private void servo180jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_servo180jSlider1StateChanged
    // TODO add your handling code here:
  }//GEN-LAST:event_servo180jSlider1StateChanged

  private void servo180jSlider1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_servo180jSlider1PropertyChange
    // TODO add your handling code here:
  }//GEN-LAST:event_servo180jSlider1PropertyChange

  private void multiLookupjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiLookupjButtonActionPerformed
    // TODO add your handling code here:
    roloClientConnector.write("MULTI:SCAN");
  }//GEN-LAST:event_multiLookupjButtonActionPerformed

  private void multiScanResultsjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiScanResultsjButton1ActionPerformed
    // TODO add your handling code here:
    roloClientConnector.write("MULTI:SCAN-RESULTS");
  }//GEN-LAST:event_multiScanResultsjButton1ActionPerformed

  private void multiScanStopjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiScanStopjButtonActionPerformed
    // TODO add your handling code here:
    roloClientConnector.write("MULTI:SCAN-STOP");
  }//GEN-LAST:event_multiScanStopjButtonActionPerformed

  private void multiScanCleanjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiScanCleanjButtonActionPerformed
    // TODO add your handling code here:
    roloClientConnector.write("MULTI:SCAN-CLEAN");
  }//GEN-LAST:event_multiScanCleanjButtonActionPerformed

  private void monitorMotorAjCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monitorMotorAjCheckBoxActionPerformed
    // TODO add your handling code here:
    if(monitorMotorAjCheckBox.isSelected()){
      roloClientConnector.write("MONITOR-ON:MOTORA");
    }else {
      roloClientConnector.write("MONITOR-OFF:MOTORA");
    }
  }//GEN-LAST:event_monitorMotorAjCheckBoxActionPerformed

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    // TODO add your handling code here:
    notificationjTextArea.setText("");
  }//GEN-LAST:event_jButton1ActionPerformed

  private void multiRotateLjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiRotateLjButton1ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_multiRotateLjButton1ActionPerformed

  private void multiRotateLjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiRotateLjButton2ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_multiRotateLjButton2ActionPerformed

  private void multiRotateLjButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiRotateLjButton3ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_multiRotateLjButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HardwareTestUIJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HardwareTestUIJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HardwareTestUIJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HardwareTestUIJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HardwareTestUIJFrame().setVisible(true);
            }
        });
    }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton backwardAjButton;
  private javax.swing.JButton backwardBjButton2;
  private javax.swing.JButton backwardCjButton1;
  private javax.swing.JButton backwardGlobaljButton;
  private javax.swing.JButton backwardGlobaljButton2;
  private javax.swing.JButton connectjButton;
  private javax.swing.JCheckBox distanceEnabledjCheckBox;
  private javax.swing.JTextField distancejTextField;
  private javax.swing.JButton forwardAjButton;
  private javax.swing.JButton forwardBjButton2;
  private javax.swing.JButton forwardCjButton1;
  private javax.swing.JButton forwardGlobaljButton;
  private javax.swing.JCheckBox globalEnabledjCheckBox;
  private javax.swing.JButton jButton1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JPanel jPanel5;
  private javax.swing.JPanel jPanel6;
  private javax.swing.JPanel jPanel7;
  private javax.swing.JPanel jPanel8;
  private javax.swing.JPanel jPanel9;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JCheckBox lightEnabledjCheckBox;
  private javax.swing.JTextField lightjTextField;
  private javax.swing.JCheckBox localjCheckBox;
  private javax.swing.JCheckBox monitorMotorAjCheckBox;
  private javax.swing.JSlider motorAjSlider;
  private javax.swing.JSlider motorBjSlider;
  private javax.swing.JSlider motorCjSlider;
  private javax.swing.JSlider motorGlobaljSlider;
  private javax.swing.JButton multiLookupjButton;
  private javax.swing.JButton multiRotateLjButton;
  private javax.swing.JButton multiRotateLjButton1;
  private javax.swing.JButton multiRotateLjButton2;
  private javax.swing.JButton multiRotateLjButton3;
  private javax.swing.JButton multiRotateRjButton;
  private javax.swing.JButton multiScanCleanjButton;
  private javax.swing.JButton multiScanResultsjButton1;
  private javax.swing.JButton multiScanStopjButton;
  private javax.swing.JTextArea notificationjTextArea;
  private javax.swing.JTextField serverAddressjTextField;
  private javax.swing.JButton servo180CenterjButton1;
  private javax.swing.JSlider servo180jSlider1;
  private javax.swing.JButton servo180rightjButton1;
  private javax.swing.JLabel statusjLabel;
  private javax.swing.JButton stopAjButton;
  private javax.swing.JButton stopBjButton2;
  private javax.swing.JButton stopCjButton1;
  private javax.swing.JButton stopGlobaljButton;
  private javax.swing.JCheckBox touchEnabledjCheckBox;
  private javax.swing.JTextField touchjTextField;
  // End of variables declaration//GEN-END:variables
    
}
