/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.salaboy.rolo.hardware.test.ui;

import com.salaboy.rolo.the.robot.comm.CommandClientHandler;
import com.salaboy.rolo.the.robot.comm.RoloClientConnector;
import com.salaboy.rolo.the.robot.comm.UIView;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JTextField;
import org.hornetq.api.core.client.ClientSession;

/**
 *
 * @author salaboy
 */
public class SimpleMotorTestUIJFrame extends javax.swing.JFrame implements UIView {

    private RoloClientConnector roloClientConnector;
    private boolean connected = false;

    /**
     * Creates new form SimpleMotorTest
     */
    public SimpleMotorTestUIJFrame() {
        initComponents();
        roloClientConnector = new RoloClientConnector("rolo-ui", new CommandClientHandler(this));
    }

    public JTextField getStatusjTextField() {
        return statusjTextField;
    }

    public JTextField getRotateDegreesjTextField() {
        return rotateDegreesjTextField;
    }

    public JTextField getSpeedjTextField() {
        return speedjTextField;
    }

    public JTextField getAngleMonitorjTextField() {
        return angleMonitorjTextField;
    }

    public JTextField getServerAddressjTextField() {
        return serverAddressjTextField;
    }

    public JTextField getSpeedMonitorjTextField() {
        return speedMonitorjTextField;
    }

    public JLabel getStatusjLabel() {
        return statusjLabel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        directionButtonGroup = new javax.swing.ButtonGroup();
        breakButtonGroup = new javax.swing.ButtonGroup();
        pidDirectionButtonGroup = new javax.swing.ButtonGroup();
        pidRotateButtonGroup = new javax.swing.ButtonGroup();
        leftRightMotorSelectionbuttonGroup = new javax.swing.ButtonGroup();
        jTabbedPane = new javax.swing.JTabbedPane();
        controljPanel = new javax.swing.JPanel();
        jPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        forwardjButton = new javax.swing.JButton();
        backwardjButton = new javax.swing.JButton();
        stopjButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        rotateBackwardjRadioButton = new javax.swing.JRadioButton();
        rotateForwardjRadioButton = new javax.swing.JRadioButton();
        breakjRadioButton = new javax.swing.JRadioButton();
        coastjRadioButton = new javax.swing.JRadioButton();
        rotateDegreesjTextField = new javax.swing.JTextField();
        rotatejButton = new javax.swing.JButton();
        leftMotorjRadioButton = new javax.swing.JRadioButton();
        rightMotorjRadioButton = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        speedjTextField = new javax.swing.JTextField();
        setSpeedjButton = new javax.swing.JButton();
        monitorjPanel = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        speedMonitorjTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        angleMonitorjTextField = new javax.swing.JTextField();
        getSpeedjButton = new javax.swing.JButton();
        resetAnglejButton = new javax.swing.JButton();
        getAnglejButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        statusjTextField = new javax.swing.JTextField();
        statusjButton = new javax.swing.JButton();
        pidjPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        pidDegresjTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        pidDistancejTextField = new javax.swing.JTextField();
        pidRotateRightjRadioButton = new javax.swing.JRadioButton();
        pidRotateLeftjRadioButton = new javax.swing.JRadioButton();
        moveForwardjRadioButton = new javax.swing.JRadioButton();
        moveBackwardjRadioButton = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        rotatePIDjButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        wheelsDiamjTextField = new javax.swing.JTextField();
        setDiamjButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        wheelDistancejTextField = new javax.swing.JTextField();
        setDistjButton = new javax.swing.JButton();
        connectionjPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        connectjButton = new javax.swing.JButton();
        statusjLabel = new javax.swing.JLabel();
        serverAddressjTextField = new javax.swing.JTextField();
        localjCheckBox = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Controls"));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Individual Motor"));

        forwardjButton.setText("Forward");
        forwardjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forwardjButtonActionPerformed(evt);
            }
        });

        backwardjButton.setText("Backward");
        backwardjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backwardjButtonActionPerformed(evt);
            }
        });

        stopjButton.setText("Stop");
        stopjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopjButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Degrees");

        directionButtonGroup.add(rotateBackwardjRadioButton);
        rotateBackwardjRadioButton.setText("Backward");

        directionButtonGroup.add(rotateForwardjRadioButton);
        rotateForwardjRadioButton.setSelected(true);
        rotateForwardjRadioButton.setText("Forward");

        breakButtonGroup.add(breakjRadioButton);
        breakjRadioButton.setSelected(true);
        breakjRadioButton.setText("Break");
        breakjRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                breakjRadioButtonActionPerformed(evt);
            }
        });

        breakButtonGroup.add(coastjRadioButton);
        coastjRadioButton.setText("Coast");

        rotateDegreesjTextField.setText("90");

        rotatejButton.setText("Rotate");
        rotatejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rotatejButtonActionPerformed(evt);
            }
        });

        leftRightMotorSelectionbuttonGroup.add(leftMotorjRadioButton);
        leftMotorjRadioButton.setSelected(true);
        leftMotorjRadioButton.setText("Left Motor");

        leftRightMotorSelectionbuttonGroup.add(rightMotorjRadioButton);
        rightMotorjRadioButton.setText("Right Motor");

        jLabel1.setText("Speed");

        speedjTextField.setText("255");

        setSpeedjButton.setText("Set Speed");
        setSpeedjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setSpeedjButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(forwardjButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(backwardjButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(stopjButton))
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(leftMotorjRadioButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(rightMotorjRadioButton))
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(6, 6, 6)
                        .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel3Layout.createSequentialGroup()
                                .add(jLabel1)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(speedjTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 90, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(setSpeedjButton)
                                .add(0, 0, Short.MAX_VALUE))
                            .add(jPanel3Layout.createSequentialGroup()
                                .add(jLabel2)
                                .add(18, 18, 18)
                                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(rotateForwardjRadioButton)
                                    .add(breakjRadioButton))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(coastjRadioButton)
                                    .add(jPanel3Layout.createSequentialGroup()
                                        .add(rotateBackwardjRadioButton)
                                        .add(8, 8, 8)
                                        .add(rotateDegreesjTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 90, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                        .add(rotatejButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)))))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(leftMotorjRadioButton)
                    .add(rightMotorjRadioButton))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(forwardjButton)
                    .add(backwardjButton)
                    .add(stopjButton))
                .add(2, 2, 2)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(rotateForwardjRadioButton)
                    .add(rotateBackwardjRadioButton)
                    .add(rotatejButton)
                    .add(rotateDegreesjTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(breakjRadioButton)
                    .add(coastjRadioButton))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(speedjTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(setSpeedjButton))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout jPanelLayout = new org.jdesktop.layout.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelLayout.createSequentialGroup()
                .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 188, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout controljPanelLayout = new org.jdesktop.layout.GroupLayout(controljPanel);
        controljPanel.setLayout(controljPanelLayout);
        controljPanelLayout.setHorizontalGroup(
            controljPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(controljPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        controljPanelLayout.setVerticalGroup(
            controljPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(controljPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane.addTab("Control", controljPanel);

        monitorjPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Monitor"));

        jLabel3.setText("Speed");

        jLabel4.setText("Angle");

        getSpeedjButton.setText("Get Speed");
        getSpeedjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getSpeedjButtonActionPerformed(evt);
            }
        });

        resetAnglejButton.setText("Reset Angle");
        resetAnglejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetAnglejButtonActionPerformed(evt);
            }
        });

        getAnglejButton.setText("Get Angle");
        getAnglejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getAnglejButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Status");

        statusjButton.setText("Get Status");
        statusjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusjButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel6Layout = new org.jdesktop.layout.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel6Layout.createSequentialGroup()
                        .add(jLabel4)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(angleMonitorjTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 108, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 25, Short.MAX_VALUE)
                        .add(getAnglejButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(resetAnglejButton)
                        .add(80, 80, 80))
                    .add(jPanel6Layout.createSequentialGroup()
                        .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel6Layout.createSequentialGroup()
                                .add(jLabel5)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(statusjTextField))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel6Layout.createSequentialGroup()
                                .add(jLabel3)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(speedMonitorjTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 108, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(26, 26, 26)
                        .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(getSpeedjButton)
                            .add(statusjButton))
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel6Layout.createSequentialGroup()
                .add(7, 7, 7)
                .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(statusjTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(statusjButton))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(speedMonitorjTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(getSpeedjButton))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(angleMonitorjTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(resetAnglejButton)
                    .add(getAnglejButton))
                .addContainerGap(274, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout monitorjPanelLayout = new org.jdesktop.layout.GroupLayout(monitorjPanel);
        monitorjPanel.setLayout(monitorjPanelLayout);
        monitorjPanelLayout.setHorizontalGroup(
            monitorjPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(monitorjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        monitorjPanelLayout.setVerticalGroup(
            monitorjPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(monitorjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane.addTab("Monitor", monitorjPanel);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Controls"));

        jLabel6.setText("Degrees");

        jLabel7.setText("Distance");

        pidRotateButtonGroup.add(pidRotateRightjRadioButton);
        pidRotateRightjRadioButton.setSelected(true);
        pidRotateRightjRadioButton.setText("right");

        pidRotateButtonGroup.add(pidRotateLeftjRadioButton);
        pidRotateLeftjRadioButton.setText("left");

        pidDirectionButtonGroup.add(moveForwardjRadioButton);
        moveForwardjRadioButton.setSelected(true);
        moveForwardjRadioButton.setText("forward");

        pidDirectionButtonGroup.add(moveBackwardjRadioButton);
        moveBackwardjRadioButton.setText("backward");

        jButton1.setText("move");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        rotatePIDjButton.setText("rotate");
        rotatePIDjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rotatePIDjButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(19, 19, 19)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jLabel7)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(pidDistancejTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 108, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(moveForwardjRadioButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(moveBackwardjRadioButton))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jLabel6)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(pidDegresjTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 106, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(pidRotateRightjRadioButton)
                        .add(18, 18, 18)
                        .add(pidRotateLeftjRadioButton)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(rotatePIDjButton)
                    .add(jButton1))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel6)
                    .add(pidDegresjTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(pidRotateRightjRadioButton)
                    .add(pidRotateLeftjRadioButton)
                    .add(rotatePIDjButton))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel7)
                    .add(pidDistancejTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(moveForwardjRadioButton)
                    .add(moveBackwardjRadioButton)
                    .add(jButton1))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Config"));

        jLabel8.setText("Wheel Diameter");

        setDiamjButton.setText("Set Diam");
        setDiamjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setDiamjButtonActionPerformed(evt);
            }
        });

        jLabel9.setText("Wheel Distance");

        setDistjButton.setText("Set Dist");
        setDistjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setDistjButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(40, 40, 40)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel8)
                    .add(jLabel9))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(wheelsDiamjTextField)
                    .add(wheelDistancejTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                .add(12, 12, 12)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(setDiamjButton)
                    .add(setDistjButton))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel8)
                    .add(wheelsDiamjTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(setDiamjButton))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel9)
                    .add(wheelDistancejTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(setDistjButton)))
        );

        org.jdesktop.layout.GroupLayout pidjPanelLayout = new org.jdesktop.layout.GroupLayout(pidjPanel);
        pidjPanel.setLayout(pidjPanelLayout);
        pidjPanelLayout.setHorizontalGroup(
            pidjPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pidjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(pidjPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pidjPanelLayout.setVerticalGroup(
            pidjPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, pidjPanelLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(169, 169, 169))
        );

        jTabbedPane.addTab("PID", pidjPanel);

        connectionjPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Connection"));

        connectjButton.setText("Connect");
        connectjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectjButtonActionPerformed(evt);
            }
        });

        statusjLabel.setForeground(new java.awt.Color(255, 0, 0));
        statusjLabel.setText("Disconnected");

        serverAddressjTextField.setText("127.0.0.1");

        localjCheckBox.setText("Local");
        localjCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localjCheckBoxActionPerformed(evt);
            }
        });

        jLabel10.setText("Status");

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .add(serverAddressjTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 117, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(localjCheckBox)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(connectjButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 24, Short.MAX_VALUE)
                .add(jLabel10)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(statusjLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 113, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(statusjLabel)
                    .add(serverAddressjTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(localjCheckBox)
                    .add(connectjButton)
                    .add(jLabel10))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout connectionjPanelLayout = new org.jdesktop.layout.GroupLayout(connectionjPanel);
        connectionjPanel.setLayout(connectionjPanelLayout);
        connectionjPanelLayout.setHorizontalGroup(
            connectionjPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(connectionjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        connectionjPanelLayout.setVerticalGroup(
            connectionjPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(connectionjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(353, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Connection", connectionjPanel);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jTabbedPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jTabbedPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void forwardjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forwardjButtonActionPerformed
        // TODO add your handling code here:
        if (leftMotorjRadioButton.isSelected()) {
            roloClientConnector.write("FORWARD-A:" + speedjTextField.getText());
        } else if (rightMotorjRadioButton.isSelected()) {
            roloClientConnector.write("FORWARD-B:" + speedjTextField.getText());
        }
    }//GEN-LAST:event_forwardjButtonActionPerformed

    private void backwardjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backwardjButtonActionPerformed
        // TODO add your handling code here:
        if (leftMotorjRadioButton.isSelected()) {
            roloClientConnector.write("BACKWARD-A:" + speedjTextField.getText());
        } else if (rightMotorjRadioButton.isSelected()) {
            roloClientConnector.write("BACKWARD-B:" + speedjTextField.getText());
        }
    }//GEN-LAST:event_backwardjButtonActionPerformed

    private void rotatejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rotatejButtonActionPerformed
        // TODO add your handling code here:
        String direction = "forward";
        String breaking = "break";
        if (rotateBackwardjRadioButton.isSelected()) {
            direction = "backward";
        }
        if (coastjRadioButton.isSelected()) {
            breaking = "coast";
        }
        if (leftMotorjRadioButton.isSelected()) {
            roloClientConnector.write("ROTATE-A:" + rotateDegreesjTextField.getText() + ":" + direction + ":" + breaking);
        } else if (rightMotorjRadioButton.isSelected()) {
            roloClientConnector.write("ROTATE-B:" + rotateDegreesjTextField.getText() + ":" + direction + ":" + breaking);
        }
    }//GEN-LAST:event_rotatejButtonActionPerformed

    private void connectjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectjButtonActionPerformed
        // TODO add your handling code here:
        if (!connected) {
            connected = roloClientConnector.connect(serverAddressjTextField.getText(), 5445);
            if (connected) {
                statusjLabel.setText("Connected");
                statusjLabel.setForeground(Color.green);
                connectjButton.setText("Disconnect");
            }
        } else {
            try {
                roloClientConnector.disconnect();
            } catch (Exception ex) {
                Logger.getLogger(HardwareTestUIJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            connectjButton.setText("Connect");
            statusjLabel.setText("Disconnected");
            statusjLabel.setForeground(Color.red);
        }
    }//GEN-LAST:event_connectjButtonActionPerformed

    private void localjCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localjCheckBoxActionPerformed
        // TODO add your handling code here:
        if (localjCheckBox.isSelected()) {
            serverAddressjTextField.setText("127.0.0.1");
        } else {
            serverAddressjTextField.setText("192.168.0.x");
        }
    }//GEN-LAST:event_localjCheckBoxActionPerformed

    private void stopjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopjButtonActionPerformed
        // TODO add your handling code here:

        if (leftMotorjRadioButton.isSelected()) {
            roloClientConnector.write("STOP-A:");
        } else if (rightMotorjRadioButton.isSelected()) {
            roloClientConnector.write("STOP-B:");
        }

    }//GEN-LAST:event_stopjButtonActionPerformed

    private void setSpeedjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setSpeedjButtonActionPerformed
        // TODO add your handling code here:
        if (leftMotorjRadioButton.isSelected()) {
            roloClientConnector.write("SETSPEED-A:" + speedjTextField.getText());
        } else if (rightMotorjRadioButton.isSelected()) {
            roloClientConnector.write("SETSPEED-B:" + speedjTextField.getText());
        }
    }//GEN-LAST:event_setSpeedjButtonActionPerformed

    private void getSpeedjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getSpeedjButtonActionPerformed
        // TODO add your handling code here:
        roloClientConnector.write("GETSPEED-A:");
    }//GEN-LAST:event_getSpeedjButtonActionPerformed

    private void resetAnglejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetAnglejButtonActionPerformed
        // TODO add your handling code here:
        roloClientConnector.write("RESET-A:");
    }//GEN-LAST:event_resetAnglejButtonActionPerformed

    private void getAnglejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getAnglejButtonActionPerformed
        // TODO add your handling code here:
        roloClientConnector.write("READ-A:");
    }//GEN-LAST:event_getAnglejButtonActionPerformed

    private void statusjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusjButtonActionPerformed
        // TODO add your handling code here:
        roloClientConnector.write("STATUS-A:");
    }//GEN-LAST:event_statusjButtonActionPerformed

    private void breakjRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_breakjRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_breakjRadioButtonActionPerformed

    private void rotatePIDjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rotatePIDjButtonActionPerformed
        // TODO add your handling code here:
        String direction = "right";
        if (pidRotateLeftjRadioButton.isSelected()) {
            direction = "left";
        }
        roloClientConnector.write("ROTATE-FRONT_WHEELS:" + direction + ":" + pidDegresjTextField.getText());
    }//GEN-LAST:event_rotatePIDjButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String direction = "forward";
        if (moveBackwardjRadioButton.isSelected()) {
            direction = "backward";
        }
        roloClientConnector.write("MOVE-FRONT_WHEELS:" + direction + ":" + pidDistancejTextField.getText());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void setDiamjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setDiamjButtonActionPerformed
        // TODO add your handling code here:
        roloClientConnector.write("SETDIAM-FRONT_WHEELS:" + wheelsDiamjTextField.getText());
    }//GEN-LAST:event_setDiamjButtonActionPerformed

    private void setDistjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setDistjButtonActionPerformed
        // TODO add your handling code here:
        roloClientConnector.write("SETDIST-FRONT_WHEELS:" + wheelDistancejTextField.getText());
    }//GEN-LAST:event_setDistjButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimpleMotorTestUIJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimpleMotorTestUIJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimpleMotorTestUIJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimpleMotorTestUIJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimpleMotorTestUIJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField angleMonitorjTextField;
    private javax.swing.JButton backwardjButton;
    private javax.swing.ButtonGroup breakButtonGroup;
    private javax.swing.JRadioButton breakjRadioButton;
    private javax.swing.JRadioButton coastjRadioButton;
    private javax.swing.JPanel connectionjPanel;
    private javax.swing.JButton connectjButton;
    private javax.swing.JPanel controljPanel;
    private javax.swing.ButtonGroup directionButtonGroup;
    private javax.swing.JButton forwardjButton;
    private javax.swing.JButton getAnglejButton;
    private javax.swing.JButton getSpeedjButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JRadioButton leftMotorjRadioButton;
    private javax.swing.ButtonGroup leftRightMotorSelectionbuttonGroup;
    private javax.swing.JCheckBox localjCheckBox;
    private javax.swing.JPanel monitorjPanel;
    private javax.swing.JRadioButton moveBackwardjRadioButton;
    private javax.swing.JRadioButton moveForwardjRadioButton;
    private javax.swing.JTextField pidDegresjTextField;
    private javax.swing.ButtonGroup pidDirectionButtonGroup;
    private javax.swing.JTextField pidDistancejTextField;
    private javax.swing.ButtonGroup pidRotateButtonGroup;
    private javax.swing.JRadioButton pidRotateLeftjRadioButton;
    private javax.swing.JRadioButton pidRotateRightjRadioButton;
    private javax.swing.JPanel pidjPanel;
    private javax.swing.JButton resetAnglejButton;
    private javax.swing.JRadioButton rightMotorjRadioButton;
    private javax.swing.JRadioButton rotateBackwardjRadioButton;
    private javax.swing.JTextField rotateDegreesjTextField;
    private javax.swing.JRadioButton rotateForwardjRadioButton;
    private javax.swing.JButton rotatePIDjButton;
    private javax.swing.JButton rotatejButton;
    private javax.swing.JTextField serverAddressjTextField;
    private javax.swing.JButton setDiamjButton;
    private javax.swing.JButton setDistjButton;
    private javax.swing.JButton setSpeedjButton;
    private javax.swing.JTextField speedMonitorjTextField;
    private javax.swing.JTextField speedjTextField;
    private javax.swing.JButton statusjButton;
    private javax.swing.JLabel statusjLabel;
    private javax.swing.JTextField statusjTextField;
    private javax.swing.JButton stopjButton;
    private javax.swing.JTextField wheelDistancejTextField;
    private javax.swing.JTextField wheelsDiamjTextField;
    // End of variables declaration//GEN-END:variables

    @Override
    public void messageReceived(ClientSession session, Object message, String producerId) throws Exception {
        System.out.println(">>> Client Handler Message Recieved = " + message);
        String[] values = message.toString().split(":");
        if (values[0].equals("SPEED_REPORT")) {
            getSpeedMonitorjTextField().setText(values[1]);
        }
        if (values[0].equals("ANGLE_REPORT")) {
            getAngleMonitorjTextField().setText(values[1]);
        }
        if (values[0].equals("STATUS_REPORT")) {
            getStatusjTextField().setText(values[1]);
        }
    }
}
